---
- name: Change swappiness to 0
  ansible.posix.sysctl:
    name: vm.swappiness
    value: 0
    state: present

- name: Stripe suid from Core dumps
  ansible.posix.sysctl:
    name: fs.suid_dumpable
    value: 0
    state: present

- name: Disable unused network features
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 0
    state: present
  loop:
    - net.ipv4.ip_forward
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
    - net.ipv4.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects

- name: Enable additional network security measures
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  loop:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians
    - net.ipv4.icmp_echo_ignore_broadcasts
    - net.ipv4.icmp_ignore_bogus_error_responses
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

